### ISSUE TITLE
ImportError: /usr/local/lib/libgnuradio-tpms.so: undefined symbol: _ZN2gr3fft6window7hanningEi

### ISSUE THREAD

**Issue by kf4nvx** [jboone/gr-tpms#5]
After going thru the steps several times and adding all the dependencies to get this package installed, I finally got it installed without error. After doing so I get this error.

_$ sudo tpms_rx --source rtlsdr --if-rate 400000 --tuned-frequency 315000000_
Traceback (most recent call last):
  File "/usr/local/bin/tpms_rx", line 38, in <module>
    import tpms
  File "/usr/local/lib/python2.7/dist-packages/tpms/**init**.py", line 44, in <module>
    from tpms_swig import *
  File "/usr/local/lib/python2.7/dist-packages/tpms/tpms_swig.py", line 26, in <module>
    _tpms_swig = swig_import_helper()
  File "/usr/local/lib/python2.7/dist-packages/tpms/tpms_swig.py", line 22, in swig_import_helper
    _mod = imp.load_module('_tpms_swig', fp, pathname, description)
**ImportError: /usr/local/lib/libgnuradio-tpms.so: undefined symbol: _ZN2gr3fft6window7hanningEi**

I tried installing gr-tpms from the beginning again following all the steps again and the same problem remains. 

From what I have been able to google for an _ImportError: \*  undefined symbol_ problem I have verified this:
 /usr/local/lib is redundantly included in /etc/ld.so.conf as it is also called within /etc/ld.so.conf.d/*.conf. 
Also, ran ldconfig as sudo.

System Info:
**uname -a**
Linux failbox 3.2.0-80-generic #116-Ubuntu SMP Mon Mar 23 17:11:03 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
**python --version**
Python 2.7.3
**gnuradio-config-info --version**
3.7.5

I feel what I am missing is simple but am hitting a wall!!

Thanks,
Jonathan

**Comment by jboone** [comment]
Sorry for the delay. It appears that gr::fft::window::hanning is defined for both 3.7.5 (what you're using) and 3.7.8 (what I'm currently building against). However, it turns out to be an alias for the Hann function, and that might possibly be causing your trouble. I'm reviewing my choice of windowing functions anyway, and will switch to a name that's not aliased to another function.

For now, try the window function rename commit I just pushed: 849254874d8f4b7f8fa748ca2437b43664b6da88

**Comment by jboone** [comment]
Closing, as I'm assuming the fix either worked, or things have otherwise changed or become irrelevant.
